### ISSUE TITLE
Adding feature to the app

### ISSUE THREAD

**Issue by calvin138** [SimpleMobileTools/Simple-Calculator#101]
I have several features that I wish to add to this app, which is
1. To be able to see history
2. To add more equation function, such as Sin() Cos() Tan()
3. To be able to put the current equation on hold for later use
4. To be able to export history into a .txt file for sharing with others.

That's all the features I wish to add, Thank you.

**Comment by calvin138** [comment]
This is for my school assignment

**Comment by tibbi** [comment]
1. it is already reported
2. a more advanced scientific calculator has already been reported, that would require a bigger change
3,4 - I dont want those
