### ISSUE TITLE
Multiplication/division with negative numbers

### ISSUE THREAD

**Issue by Atalanttore** [SimpleMobileTools/Simple-Calculator#104]
Hi

I wanted to do a multiplication or division with negative numbers, but Simple Calculator v4.1.0 doesn't recognize the arithmetic operator for multiplication or division in between negative numbers.

Examples:
Entering **-100 / -5** will become to **-100 -5** = -105
Entering **-100 * -5** will become to **-100 -5** = -105

**Comment by braincident** [comment]
I think it's because the APP can only read and store one operator, so when you input the "-" of "-5", it will become "-100-5".

**Comment by tibbi** [comment]
changing it isnt really planned now, might work weirdly.
