### ISSUE TITLE
Make symbols appear in input

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Calculator#123]
For example if you type "5+2" only "5" appears in input window. It would be more intuitive and more mistake-proof if all your inputs appeared on-screen in real time.

**Comment by studentPavel** [comment]
Hi, is it still available? Could you assign it to me?

**Comment by tibbi** [comment]
ye, work on it if you want

**Comment by studentPavel** [comment]
Ok, I will work on it.

**Comment by studentPavel** [comment]
Hi, @tibbi I have looked on it. Look on my comment in PR. I think it could work. There are many combinations which should be tested - so I don't know if there is any bug. The functionality was not described in detail - so this is my solution. I think firstly you will notice that user must calculate that zero is entered at the beginning - but i have explained it in comment (I wanted to keep that user can start with some operation, so first number is zero).

Taka a look at it :-)

**Comment by tibbi** [comment]
will take a look at it later, not working on this app nowadays. Thanks

**Comment by studentPavel** [comment]
@tibbi Hi Tibi I want also to take a look at some test or integrate some devops service on my branch, but i have find few problems with tests... Some imports or how to start the main activity in setup method (src/test/java/com/simplemobiletools/calculator/MainActivityTest.kt) is deprecated, what do you think?

**Comment by tibbi** [comment]
I removed all tests from the app already, dont like them at all. So I cannot really help with them.

**Comment by studentPavel** [comment]
@tibbi and i just would like to ask about branch: patch-1 what have you created in my fork, purpose was only that i could see which changed you have added to mine? can i delete this branch?

**Comment by tibbi** [comment]
yep, you can

**Comment by tibbi** [comment]
this has been added already
