### ISSUE TITLE
0^0 returns 0

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Calculator#125]
Should be invalid expression, contrary to what Google's, Microsoft's and 95% other calculators say.

**Comment by Phoenix1747** [comment]
0^0 is a bit of a problem since it's not really fixed to be either 0 or 1 (indeterminate form). However the common definition today is that 0^0 = 1.

https://www.quora.com/What-is-0-0-the-zeroth-power-of-zero-1
http://mathforum.org/dr.math/faq/faq.0.to.0.power.html

**Comment by vyasknellutla** [comment]
Testing it as of now, it returns 1, so unless we want it to be considered Not a Number I think that it can be closed
