### ISSUE TITLE
app crashing during sqrt operation

### ISSUE THREAD

**Issue by halon176** [SimpleMobileTools/Simple-Calculator#127]
Non ho esattamente chiaro quasi sia l'operazione che sta cercando di eseguire. Se il risultato dell'operazione precedente è un numero negativo e l'operazione successiva è una radice l'applicazione va in crash.
Esempio di sequenza che manda in crash: -1 = then sqrt (any number) instantly closes app

***app version:*** 5.0.2

**Comment by Phoenix1747** [comment]
Using the same version and I only get a `NaN` output, no crash.

**Comment by tibbi** [comment]
should be ok in 5.5.0+
