### ISSUE TITLE
whenever i use more than one operands the application crashes.

### ISSUE THREAD

**Issue by Singh-Priyansh** [SimpleMobileTools/Simple-Calculator#160]
![Screenshot_1593168372](https://user-images.githubusercontent.com/66729436/85850805-267a1300-b7cb-11ea-81f7-70a4420b25d4.png)
this is my simple java calculator.
if i do small calculation like:
9+1
7*2
6/2
it works absolutely fine, but if i enter two operands it crashes
like if i enter "9+1"  and after i enter another "+" the application crash.
Please Help!!!

**Comment by tibbi** [comment]
this isnt our app... Im not giving support for other apps, just read the crashdump.
