### ISSUE TITLE
Make sure √9= doesnt convert into 9√9

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calculator#185]

**Comment by licia-tia** [comment]
all √n= is n√n

**Comment by theAkito** [comment]
This issue causes another issue: if you try to type (not calculate!) `0√` then the app crashes. Also happens in the widget, but then it just becomes "unresponsive", because the user is not notified of the crash.

**Comment by tibbi** [comment]
should be fixed in 5.5.0. There will be a "1" added in front of √ for now, so it wont need a big rewrite :)
