### ISSUE TITLE
Wrong behavior when computing a square root of a negative number

### ISSUE THREAD

**Issue by braincident** [SimpleMobileTools/Simple-Calculator#191]
If I input a negative number like -9, then strike the √ key, the APP will crash rather than output error, or even output 0 instead, like when computing power of large numbers.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by braincident** [comment]
It's v5.30.

**Comment by tibbi** [comment]
retry with 5.4, root behaviour has changed
