### ISSUE TITLE
The result of 0%0% is -NaN

### ISSUE THREAD

**Issue by licia-tia** [SimpleMobileTools/Simple-Calculator#196]
![bug5](https://user-images.githubusercontent.com/22077929/102685468-cd3fe900-421b-11eb-905b-e9f43e1c2a8d.gif)

**Comment by tibbi** [comment]
what app version are you using?

**Comment by licia-tia** [comment]
v5.4.0，bc9753e02fda7e42da4bf04b3a716c125a3b5852
