### ISSUE TITLE
[BUG] Mod wrong result

### ISSUE THREAD

**Issue by Kaivanov21** [SimpleMobileTools/Simple-Calculator#204]
Steps to Replicate: if we enter n%n% it's not giving zero as expected, but 0.01

Expected behavior: result should be 0
or not to allow enter second % sign because it's cause some other problems yet.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/55892883/106339308-dd2cfd00-629e-11eb-985f-5fecd82aa44f.gif)

**Comment by tibbi** [comment]
will be fixed in 5.6.0
