### ISSUE TITLE
[BUG] Crash after putting second sign after mod 0

### ISSUE THREAD

**Issue by Kaivanov21** [SimpleMobileTools/Simple-Calculator#218]
**Steps to Replicate:**

1. Tap 5 (or any other digit)
2. Tap %
3. Tap 0 
4. Tap - (or any other sign except =)
5. _Then you get "An unknown error occured" toast_ 
(Because it is calculates the result of 5%0 then we put new sign and gets error)
6. Tap any number
7. Tap any sign
8. App is crashed

**Expected behavior:** 
It should not allow to put new sign after showing toast "An unknown error occured".
The problem is that we allow to put new sign and numbers then mod 0 calls error, and this case is not catched well and causes crash.

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/55892883/134999599-f9c9fb6a-30df-4c72-ba9d-e1c10ebe4389.gif)

**Comment by tibbi** [comment]
seems to be fixed already
