### ISSUE TITLE
Crashes when calculating huge numbers and then using any operation

### ISSUE THREAD

**Issue by AlexanderFL** [SimpleMobileTools/Simple-Calculator#224]
**How to replicate**

1. Continuously raise a number to some power
2. Result of the operation is too big, "unknown error occurred" is displayed (result is infinite)
3. Try to use any operation after that without clearing the screen and the app crashes (fx. - 1)

![Gif of these steps](https://user-images.githubusercontent.com/24865043/141683582-d496255e-a15f-4cc4-9601-3c3f5870e301.gif)

**Expected result**
Most important is that the app shouldn't crash, and instead maybe display the latest valid result

**Comment by tibbi** [comment]
the attachment is invalid, what do you mean by huge numbers?

**Comment by AlexanderFL** [comment]
Odd, link seems to work fine for me. By huge numbers I mean like the result from 9^9^9 which has roughly 400 million digits

**Comment by tibbi** [comment]
oh man, dont expect having support for such numbers, this is not a superscientific calculator

**Comment by AlexanderFL** [comment]
I'm aware that this is a silly use case, but still think that the app shouldn't crash from the results

**Comment by AlexanderFL** [comment]
The issue itself is not that that the number itself is huge, it's when the result of the operation is infinite (in the eyes of the computer), the input isn't updated. So next time when a user inputs any arithmetic operation, [getSecondValue()](https://github.com/SimpleMobileTools/Simple-Calculator/blob/2c04843742a680db542eeaf76dc417ca817ab764/app/src/main/kotlin/com/simplemobiletools/calculator/helpers/CalculatorImpl.kt#L160) is not trying to parse a non-float to a float resulting in the crash. I have a fix ready if you're interested

**Comment by tibbi** [comment]
try upgrading to 5.6.1 if you can still reproduce it

**Comment by AlexanderFL** [comment]
this is present in version 5.6.1 as well

**Comment by tibbi** [comment]
sure, just send the fix with a pull request if you have it. Thanks
