### ISSUE TITLE
incorrect floating point result

### ISSUE THREAD

**Issue by barbiefan** [SimpleMobileTools/Simple-Calculator#237]
doing simple arithmetic on floating point numbers with big whole part gives wrong mantissa (as expected with something like f32 numbers)
![Screenshot_20220108_162304_com simplemobiletools calculator](https://user-images.githubusercontent.com/74291618/148686663-11ece1a3-d2e9-4807-851e-7a5391b92197.jpg)

**Comment by tibbi** [comment]
can this happen at all 4 operations "+ - * /" ?

**Comment by barbiefan** [comment]
multiplication and division are fine for me (couldn't come up with expression that would produce wrong result), but both addition and subtraction aren't

**Comment by tibbi** [comment]
alright thanks, I added some fix for it. I kept finding plus and minus only at googling, we will see
