### ISSUE TITLE
App crashes unexpectedly

### ISSUE THREAD

**Issue by ynsnf** [SimpleMobileTools/Simple-Calculator#243]
#### Steps to Replicate:
1. Add Two Decimal numbers
2. Find the sum
3. Add another Number
4. App Crashes

**Comment by tibbi** [comment]
what app version are you using? It doesnt crash to me

**Comment by ynsnf** [comment]
5.7.0. The Latest Version

**Comment by tibbi** [comment]
5.7.1 is the latest one. If it still crashes there tell the exact steps and values you can reproduce it with please.

**Comment by ynsnf** [comment]
The F-droid Repo was updated and the bug is fixed now, thanks!
