### ISSUE TITLE
[BUG] Replicable crash when pressing C

### ISSUE THREAD

**Issue by prononoob** [SimpleMobileTools/Simple-Calculator#247]
If at any point you hold C for about a second so it registers as a hold and not a tap, and then tap C the app crashes, it happens every time

it's really easy to replicate:
1. hold C
2. tap C

**Comment by tibbi** [comment]
what app version are you using? It is not happening to me

**Comment by prononoob** [comment]
> what app version are you using? 

i have the latest available from fdroid, 5.7.0

**Comment by prononoob** [comment]
oh my bad i haven't updated my repos in fdroid, after update it's not crashing anymore
