### ISSUE TITLE
Resets when I switch away and then back

### ISSUE THREAD

**Issue by hamishmb** [SimpleMobileTools/Simple-Calculator#277]
Hi there,

Thanks for all the effort you've put into these great applications.

I've found that when I switch away after performing a calculation, the calculator is completely reset when I switch back. This is a bit annoying and sometimes causes me to have to re-do a set of calculations, so I think this is a worthwhile usability improvement.

EDIT: I'm using the F-Droid version, if that is important.

**Comment by tibbi** [comment]
what switching away you mean?

**Comment by hamishmb** [comment]
I meant using the app switcher to switch to a different app - sorry I didn't phrase that better.

**Comment by tibbi** [comment]
you mean without rotating the device? It isnt happening to me

**Comment by hamishmb** [comment]
Yep, no rotation.

So this is interesting - it was happening the other day, but isn't happening now. Maybe this is related to Android suspending the app when RAM is low? I'm not sure how to test that hypothesis.

**Comment by tibbi** [comment]
Im not sure, but that doesnt sound like an issue on our side. Maybe you changed some setting or a color?

**Comment by hamishmb** [comment]
Agreed, doesn't sound like your fault.

I don't think I changed any settings, but I'm not sure. I'll see if I can put a big memory load on Android and reproduce. But it's sounding like it might be Android killing and restarting the app.

If Android does that regularly on low-memory devices, it might still be worth having it always save the last calculation when switching away?

**Comment by tibbi** [comment]
I dont plan storing calculations in any permanent storage, there is a history feature already. Guess Ill close this.

**Comment by hamishmb** [comment]
Oh, I didn't realize there was a history feature. That does indeed make this completely irrelevant. Sorry for the noise.
