### ISSUE TITLE
Confusing behaviour after calculating a square root

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Calculator#28]
1. Input e.g. 9
2. Press square root button
3. Result pops up
4. Input any digit
5. Press square root button
6. Square root of 3 displayed

I'm unsure whether this is a bug, but such behaviour may seem strange for some users.

**Comment by tibbi** [comment]
calculator is not really a priority for me, ill get to it in the far future

**Comment by trubitsyn** [comment]
I know :)

**Comment by trubitsyn** [comment]
@tibbi has it been fixed by #53?

**Comment by tibbi** [comment]
i dont know :)

**Comment by tibbi** [comment]
seems to be fixed
