### ISSUE TITLE
Please add % button

### ISSUE THREAD

**Issue by jozic** [SimpleMobileTools/Simple-Calculator#29]
square root is far less used than %. as there are much more *SIMPLE* usages of % than of sr.
please add % ( or replace root button with it).thanks

**Comment by trubitsyn** [comment]
We definitely need %, but please keep the square root button.

**Comment by jozic** [comment]
oh, I just realized that you implemented it in https://github.com/SimpleMobileTools/Simple-Calculator/commit/be0dea16ae78ca1ee6ed219cd6bc3c76f2a257be
thanks! eagerly waiting for the release

**Comment by tibbi** [comment]
ye and I removed modulo. While I need it from time to time, I guess most people dont even know what it is so it shouldnt be there.

**Comment by sachincool** [comment]
hey @tibbi I think you forgot to check for the unary operations on the % 
as it requires 2 parameters `result = (baseValue / 100) * secondValue` 
if I send   6%   it should give me output   0.06 as any normal calculator.  It's fairly easy and could be a beginner issue:+1: just a reminder.

**Comment by tibbi** [comment]
what do you mean? Like 0%6 should give 0.06?

**Comment by sachincool** [comment]
So According to you, should the second value be still 0 In case of  `number %`  because with the combination of  `6 % = ` i don't get any output. although the 6%6 = works perfectly. it's just a  suggestion that single number and % should work aswell.

**Comment by tibbi** [comment]
that is already a new feature request about showing calculation result in realtime without having to press "=" or some other operation, it isnt related to %

**Comment by sachincool** [comment]
I am not stating about the  real time calculation..  haha, My whole meaning was about the  different usecases of % 
unary  Case  =   `6%` = 0.06 (needs to be opened)
binary case= `6%6`=0.36  (Works  perfectly) 
hope i am not taking much of your time.

**Comment by tibbi** [comment]
i will take a look at it when adding the realtime calculation, I still see it as a related issue :)
