### ISSUE TITLE
Bug: black background hides functional buttons

### ISSUE THREAD

**Issue by ghtesting2020** [SimpleMobileTools/Simple-Calculator#294]
In settings when customizing to pure black for "primary app color", some of the buttons like '+' '=' 'c' will also change their font color to black. If you are using a pure black for background then these become invisible. The function buttons like   '+' '=' 'c'  should be following the text font color like 0, 1, 2, 3, etc.

If you are try differentiate between the function buttons and numbers, you could use **bold** for the functions and non bold for the numbers. Or add another color source for function buttons that is separate from numbers (text color)

![1_en-US](https://user-images.githubusercontent.com/69682350/204863457-e7b02f83-2c97-4410-9263-c20211b51411.jpeg)

**Comment by tibbi** [comment]
well, there are many colors to choose from, it will always be possible to select an unreadable combination. B&W theme has a specially handled accent colors, you can use that

**Comment by ghtesting2020** [comment]
> well, there are many colors to choose from, it will always be possible to select an unreadable combination. B&W theme has a specially handled accent colors, you can use that

I am trying to use primary black, black toolbar and black background since I use OLED and it saves battery. Out of all the simple tools (I use about 6 of them) this is the only one with a problem. Because those function button colors follow the top bar "primary color"
