### ISSUE TITLE
Button form

### ISSUE THREAD

**Issue by xIUPITERx** [SimpleMobileTools/Simple-Calculator#297]
The buttons are minimally oval and not circles. I can't imagine that this is intentional. (compare it to the google calculator app)

![Screenshot_20221226_131505_Calculator.png](https://user-images.githubusercontent.com/97352673/209548342-210ddac1-b773-486b-af3c-ce756af0f93c.png)

![Screenshot_20221226_131958_Calculator.png](https://user-images.githubusercontent.com/97352673/209548368-d5e486cc-97ca-4201-b6ff-154a85adb253.png)

**Comment by tibbi** [comment]
will be changed to squiricles in 5.11.1
