### ISSUE TITLE
Input is lost when the screen rotates

### ISSUE THREAD

**Issue by Hunter16g** [SimpleMobileTools/Simple-Calculator#299]
Using 5.11.0

When auto-rotate is on, the app seems to reset whenever the screen rotates.

**Comment by Burhan7777** [comment]
will try to add this soon

**Comment by inepsie** [comment]
Hello, we are students in computer science at University Paris 8 with @westindev-lbr. In the context of our course "Contribution to free software" we will gladly contribute on this issue. @Burhan7777 have you started to work on this problem? If not, can we work on it and be assigned to it ?

**Comment by Burhan7777** [comment]
yes you can work on it

**Comment by inepsie** [comment]
#305

**Comment by tibbi** [comment]
should be fixed soon
