### ISSUE TITLE
Rewrite Calculator in Kotlin

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Calculator#34]
@tibbi once you mentioned you wanted to see Calculator written in Kotlin. So there's an issue.

**Comment by trubitsyn** [comment]
I'll be glad to help, but afraid it would be a very big PR full of many small commits. Would you mind?

**Comment by tibbi** [comment]
Heh, the calculator really wasnt popular at all, I removed it from the homepage too. It needs a lot of work, I dont really feel like spending my time on it. You can do it if you want. Just do all the rewrite locally, then create the pull request. Or if you want to do it commit by commit, just keep commiting, then `squash` it before creating the pull request. Just look up `git squash`, it will basically merge all commits into 1. Thanks
