### ISSUE TITLE
App name not translated

### ISSUE THREAD

**Issue by Phoenix1747** [SimpleMobileTools/Simple-Calculator#39]
This app is the only one of your Simple apps that doesn't use the translated app name after the installation. It just shows up as "Calculator" although the German name should be "Rechner".

**Comment by tibbi** [comment]
The app hasnt been updated since then. Im not really working on it, I probably wont be working on it anytime soon.

**Comment by Phoenix1747** [comment]
Oh ok, but what about just pusing a new version with the updated translations? :X

**Comment by tibbi** [comment]
Maybe someday, i dont really want to mess with it as nobody uses it :p

**Comment by Phoenix1747** [comment]
Well, I do .-.
