### ISSUE TITLE
Static Context field leads to memory leak

### ISSUE THREAD

**Issue by trubitsyn** [SimpleMobileTools/Simple-Calculator#41]
https://github.com/SimpleMobileTools/Simple-Calculator/blob/3a5d4e96f124655deffb0a55f8961479c858f54b/app/src/main/kotlin/com/simplemobiletools/calculator/helpers/MyWidgetProvider.kt#L27

The other static fields seem to contain references to Context too. Why to keep them static?

**Comment by tibbi** [comment]
Im going to rewrite the widget right now, it's still using the old way.

**Comment by tibbi** [comment]
I kept a static CalculatorImpl reference, couldnt make it otherwise. It keeps reseting on every button press otherwise
