### ISSUE TITLE
2.0.0 tags wrong commit

### ISSUE THREAD

**Issue by relan** [SimpleMobileTools/Simple-Calculator#42]
Version tagged as 2.0.0 has the [same version name and code as 1.12](https://github.com/SimpleMobileTools/Simple-Calculator/blob/2.0.0/app/build.gradle#L13). This prevents Simple Calculator from [being updated on F-Droid](https://gitlab.com/fdroid/fdroiddata/issues/978).

Could you delete 2.0.0 tag and tag commit a00eb5e03e10af9828037be3f1cdee3026decb64 as 2.0.0? This won't rewrite git history.

**Comment by tibbi** [comment]
updated, thanks

**Comment by relan** [comment]
Should be available on F-Droid in a few days. Thanks!
