### ISSUE TITLE
Dividing by Zero Returns Zero as a Value

### ISSUE THREAD

**Issue by thewizardstudio** [SimpleMobileTools/Simple-Calculator#68]
#### Expected Behavior
Dividing by Zero returns an Error or indication of invalid calculation.

#### Actual Behavior
Dividing by Zero returns an answer of 0.

#### How to Reproduce
1. Launch Simple Calculator 3.1.1 on Android 8.1.0
2. Tap '5' > Tap '÷' > Tap '0' > Tap '='

---
    Device: Pixel 2 XL
    OS: Android 8.1.0
    App Version: 3.1.1
---

#### Recording of the Bug
![DivideByZero.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517932443/mrq6ormeqnfiauaqrxoo.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/dividing-by-zero-returns-zero-as-a-value">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
it shows an error already for some time, so Im closing it
