### ISSUE TITLE
[Bug] Using operator before input sets first input to zero

### ISSUE THREAD

**Issue by BlackLotus** [SimpleMobileTools/Simple-Calculator#7]
If you use any operator (+,-,mod,^,...) before you input a digest you set the input to zero.
An example
The squareroot of 9 is 3. To get to this stunning conclusion you would normally press

> 9
> √

And as a result get 3.
If you press

> √
> 9
> √

You get √0
You can do this with every operator

> %
> 9
> √

**Comment by vanitasvitae** [comment]
I can confirm this. This is especialy annoying, when calculating roots, because the roots of any number appears to be zero when this bug appears.

**Comment by tibbi** [comment]
has been fixed already, will be tweaked further in 5.5.0
