### ISSUE TITLE
Add history

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Calculator#8]

**Comment by paulle** [comment]
I would like to see this feature implemented.

**Comment by Aga-C** [comment]
- How should it look like? Should it be visible as a second tab (similar to Simple Dialer and it's Call History), or how?
- What data should be shown there, and how should be placed? In OnePlus, there is a date and formula with its result, and also a button to clear the history.

**Comment by Aga-C** [comment]
@tibbi Do you have any idea how it could be implemented? Maybe I could do this functionality, but I'd like to know first how it should look.

**Comment by tibbi** [comment]
I dont know yet, I wasnt researching it. I usually test a couple apps to see which ones I like and which ones I dont. Maybe you could test some and paste some links that have it done well.

**Comment by Aga-C** [comment]
- Calculator from OnePlus; history is accessed by sliding display to the bottom:

![image](https://user-images.githubusercontent.com/85929121/148108885-2e51f75f-a304-4aa9-9e50-69042d0811de.png)

- WolframAlpha (only paid version https://play.google.com/store/apps/details?id=com.wolfram.android.alpha); history is available in the menu:

![image](https://user-images.githubusercontent.com/85929121/148109005-fdd7173b-c29b-4ed8-9d95-18142d1385e5.png)

- <https://f-droid.org/packages/org.solovyev.android.calculator/>: has a lot of options related to history (copying formula, copying result, separate tabs in history for recents and saved equations); also available in Google Play Store
- <https://play.google.com/store/apps/details?id=cz.hipercalc>: has a different way of showing history, looks a bit like handwritten equation 
- <https://play.google.com/store/apps/details?id=com.google.android.calculator>: visually modern and nice:
- <https://play.google.com/store/apps/details?id=all.in.one.calculator>: history is plain, but whole app is rich in functionality

**Comment by tibbi** [comment]
Id like to avoid some unexpected gestures, maybe a top menu button for History should do it. We have only 2 icons there anyway, a third one would fit. Then the last 10 or so operations would show up in a dialog window like file Properties.
