### ISSUE TITLE
App doesn't start after changing the theme

### ISSUE THREAD

**Issue by Avizini** [SimpleMobileTools/Simple-Calculator#86]
- Install app from fdroid
- Change theme to black and white
- Exit
- Try to launch it again

App doesn't start!

**Comment by tibbi** [comment]
some launchers dont support app icon color change properly. What launcher are you using? Is your device rooted?

**Comment by Avizini** [comment]
I am using KISS launcher, the icon color changes after I change the theme!

No, my device isn't rooted.

**Comment by tibbi** [comment]
This is a more generic issue affecting all apps, but it should be already fixed
