### ISSUE TITLE
Use regional format as decimal mark

### ISSUE THREAD

**Issue by JakeOnestone** [SimpleMobileTools/Simple-Calculator#96]
In Germany, comma `,` is used as a decimal mark and dot `.` is used as a digit grouping marker.
E.g. `1.234,56` is one thousand two hundred thirty four point five six.
<https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use>

Ideally, the decimal separator is set by the used language, but an option to change the decimal and grouping marker would clearly enhance the user experience.

**Comment by tibbi** [comment]
a toggle has been added already
